import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { AppProvider } from "@/context/AppContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        {process.env.NODE_ENV === "development" && (
          <script
            src="https://unpkg.com/react-scan/dist/auto.global.js"
            async
          />
        )}
      </head>
      <body suppressHydrationWarning={true}>
        <main className='main'>
          <AppProvider>
            <Header />
              {children}
            <Footer />
          </AppProvider>
        </main>
      </body>
    </html>
  );
}